version: '3.8'
services:
  #Nginx Service
#  web:
#    image: nginx:alpine
#    working_dir: /usr/src/app
#    depends_on:
#      - frontend
#    volumes:
#      - ./:/usr/src/app
#      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
#      - ./docker/nginx/error.log:/var/log/nginx/error.log
#    command: [ nginx-debug, '-g', 'daemon off;' ]
#    container_name: web-intro
#    ports:
#      - "8280:80"
#    networks:
#      asincronismo-network:
#        ipv4_address: 19.5.0.3
  #React
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-jsp
    restart: unless-stopped
    tty: true
    ports:
      - "3004:3000"
      - "8084:8080"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    networks:
      jsp-network:
        ipv4_address: 27.5.0.2

#Docker Networks
networks:
  jsp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 27.5.0.0/16
#Volumes
volumes:
  dbdatamc:
    driver: local